### ISSUE TITLE
AttributeError: class MultiHook has no attribute '__repr__'

### ISSUE THREAD

**Issue by jakke** [mgedmin/zodbbrowser#6]
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module zodbbrowser.browser, line 94, in __call__
  Module zodbbrowser.browser, line 153, in render
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
   - URL: /opt/plone/production_plone4/central/eggs/zodbbrowser-0.11.1-py2.7.egg/zodbbrowser/templates/zodbinfo.pt
   - Line 54, Column 12
   - Expression: <PathExpr standard:u'attr/rendered_value'>
   - Names:
      {'args': (),
       'context': <PloneSite at /toledo>,
       'default': <object object at 0x7f9aff716510>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': {},
       'request': <HTTPRequest, URL=http://xxxx.kuleuven.be:12345/toledo/@@zodbbrowser>,
       'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x5a42b90>,
       'view': <Products.Five.metaclass.ZodbInfoView object at 0x7f9adc60ebd0>,
       'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x7f9ae0896690>}
  Module zope.tales.expressions, line 217, in __call__
  Module zope.tales.expressions, line 211, in _eval
  Module zodbbrowser.browser, line 53, in rendered_value
  Module zodbbrowser.value, line 78, in render
  Module zodbbrowser.value, line 62, in _repr
AttributeError: class MultiHook has no attribute '__repr__'
```

**Comment by mgedmin** [comment]
Fix released in https://pypi.python.org/pypi/zodbbrowser/0.11.2

**Comment by jakke** [comment]
seems like it wasn't fixed completely:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module zodbbrowser.browser, line 94, in __call__
  Module zodbbrowser.browser, line 153, in render
  Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 531, in do_optTag_tal
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module zope.tales.tales, line 696, in evaluate
   - URL: /opt/plone/production_plone4/central/eggs/zodbbrowser-0.11.1-py2.7.egg/zodbbrowser/templates/zodbinfo.pt
   - Line 54, Column 12
   - Expression: <PathExpr standard:u'attr/rendered_value'>
   - Names:
      {'args': (),
       'context': <Application at >,
       'default': <object object at 0x7f5f87458510>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': {},
       'request': <HTTPRequest, URL=http://xxxx:1234/@@zodbbrowser>,
       'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x692fb90>,
       'view': <Products.Five.metaclass.ZodbInfoView object at 0x7f5f641d4c10>,
       'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0xd131150>}
  Module zope.tales.expressions, line 217, in __call__
  Module zope.tales.expressions, line 211, in _eval
  Module zodbbrowser.browser, line 53, in rendered_value
  Module zodbbrowser.value, line 78, in render
  Module zodbbrowser.value, line 62, in _repr
AttributeError: class MultiHook has no attribute '__repr__'

**Comment by mgedmin** [comment]
> URL: /opt/plone/production_plone4/central/eggs/zodbbrowser-0.11.1-py2.7.egg/zodbbrowser/templates/zodbinfo.pt

Looks like you still have 0.11.1.  The fix is in 0.11.2.

**Comment by jakke** [comment]
right, I assumed buildout would download the latest, but it didn't. Pinned it now and it's working. Thx!
